# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  - Name: Orderer
    Domain: insurance
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

# "PeerOrgs" - Definition of organizations managing peer nodes
PeerOrgs:
  - Name: Bajaj
    Domain: bajaj.com
    EnableNodeOUs: true
    Template:
      Count: 2
      # Start: 5
    Users:
      Count: 1
  - Name: BajajAllianz
    Domain: bajajallianz.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
   
